"""
Convert an EQsimu compset (one problem) into the user_defined_params.py that
EQquasi and EQdyna each read. This file is the EQsimu API to the codes: it is
the only place that knows their parameter names and on-fault array layouts,
and it checks every name against the code's defaultParameters at the pinned
commit, so a renamed parameter fails here instead of being silently dropped.
"""
import contextlib
import importlib.util
import inspect
import io
import os
import sys

UTILS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, UTILS)
import roughness

# Problem fields written to each code under the same name.
COMMON = ["mode", "fxmin", "fxmax", "fzmin", "fzmax", "dx", "ntotft",
          "vp", "vs", "rou", "friclaw", "init_norm", "creep_slip_rate",
          "fric_rsf_a", "fric_rsf_b", "fric_rsf_Dc", "fric_rsf_deltaa",
          "fric_rsf_r0", "fric_rsf_v0", "nt_out",
          "xmin_trans", "xmax_trans", "zmin_trans", "ymin_trans", "ymax_trans",
          "dx_trans"]
SHARED = {"eqquasi": COMMON + ["istart", "iend"], "eqdyna": COMMON}

# fault() keys -> on-fault array index in each code.
EQQUASI_INDEX = dict(a="FR_RSF_A", b="FR_RSF_B", Dc="FR_RSF_DC",
                     v0="FR_RSF_V0", f0="FR_RSF_F0", vini="FR_VINIT",
                     state="FR_STATE", tnrm="FR_TNRM0", tstk="FR_TSTK0")
EQDYNA_INDEX = dict(a=9, b=10, Dc=11, v0=12, f0=13, vini=46,
                    state=20, tnrm=7, tstk=8)
# In mode 2 EQdyna takes stress and state from the EQquasi restart.
EQDYNA_FROM_RESTART = ("tnrm", "tstk", "state")

ROOT_ENV = {"eqquasi": "EQQUASIROOT", "eqdyna": "EQDYNAROOT"}
COMPSET_DIR = {"eqquasi": "compset", "eqdyna": "case_input"}


class ConvertError(Exception):
    pass


def _load(path, name, extra_path=()):
    sys.path[:0] = list(extra_path)
    try:
        spec = importlib.util.spec_from_file_location(name, path)
        mod = importlib.util.module_from_spec(spec)
        with contextlib.redirect_stdout(io.StringIO()):
            spec.loader.exec_module(mod)
    finally:
        del sys.path[:len(extra_path)]
    return mod


def load_problem(compset_dir):
    mod = _load(os.path.join(compset_dir, "user_defined_params.py"),
                "eqsimu_problem", [UTILS])
    par = mod.par
    if not callable(par.fault):
        raise ConvertError(f"{compset_dir}: par.fault is not set")
    missing = [k for k in sorted(set(SHARED["eqquasi"]) | set(SHARED["eqdyna"]))
               if getattr(par, k) is None]
    if missing:
        raise ConvertError(f"{compset_dir}: unset problem fields: {missing}")
    funcs = sorted((f for f in vars(mod).values()
                    if inspect.isfunction(f) and f.__module__ == mod.__name__),
                   key=lambda f: f.__code__.co_firstlineno)
    return par, funcs


def code_parameters(code):
    root = os.environ.get(ROOT_ENV[code])
    if not root:
        raise ConvertError(f"{ROOT_ENV[code]} is not set; source checkout.sh")
    scripts = os.path.join(root, "scripts")
    return _load(os.path.join(scripts, "defaultParameters.py"),
                 "dp_" + code, [scripts])


def _lit(v, name):
    if isinstance(v, (bool, int, float, str, type(None))):
        return repr(v)
    if isinstance(v, (list, tuple)):
        return repr(v) if all(_lit(x, name) for x in v) else None
    raise ConvertError(f"{name}: cannot write a {type(v).__name__}")


def _settings(par, code, known):
    out = [(k, getattr(par, k)) for k in SHARED[code]]
    out += list(getattr(par, code).items())
    if par.roughness:
        out.append(("rough_fault", 1) if code == "eqquasi"
                   else ("insertFaultType", 3))
    unknown = [k for k, _ in out if k not in known]
    if unknown:
        raise ConvertError(f"{code} has no parameter(s) {unknown}; "
                           f"update utils/convert.py or the compset")
    return out


def _namespace(par):
    fields = sorted(set(SHARED["eqquasi"]) | set(SHARED["eqdyna"]))
    body = ",\n    ".join(f"{k}={_lit(getattr(par, k), k)}" for k in fields)
    return f"p = SimpleNamespace(\n    {body})"


def render(par, funcs, code, source):
    dp = code_parameters(code)
    known = {k for k in vars(dp.parameters) if not k.startswith("_")}
    lines = [f"# Generated by EQsimu utils/convert.py from {source}.",
             "# Do not edit: edit the EQsimu compset and recreate the case.",
             "import numpy as np",
             "from math import *",
             "from types import SimpleNamespace",
             "from defaultParameters import *" if code == "eqquasi"
             else "from defaultParameters import parameters",
             "",
             "par = parameters()"]
    lines += [f"par.{k} = {_lit(v, k)}" for k, v in _settings(par, code, known)]
    lines += ["par.dy = par.dx", "par.dz = par.dx"]
    if code == "eqdyna":
        lines += ["if par.nmat == 1:",
                  "    par.roumax, par.vmaxPML = par.rou, par.vp"]
    rnd = "int" if code == "eqquasi" else "round"
    lines += [f"par.nfx = {rnd}((par.fxmax - par.fxmin)/par.dx + 1)",
              f"par.nfz = {rnd}((par.fzmax - par.fzmin)/par.dx + 1)",
              "par.fx = np.linspace(par.fxmin, par.fxmax, par.nfx)",
              "par.fz = np.linspace(par.fzmin, par.fzmax, par.nfz)",
              "par.n_on_fault = len(par.st_coor_on_fault)",
              "par.n_off_fault = len(par.st_coor_off_fault)",
              "", _namespace(par), ""]
    lines += [inspect.getsource(f) for f in funcs]
    if code == "eqquasi":
        lines += ["par.on_fault_vars = np.zeros((par.ntotft, par.nfz, par.nfx, 100))",
                  "for ix, x in enumerate(par.fx):",
                  "    for iz, z in enumerate(par.fz):",
                  "        v = fault(p, x, z)"]
        lines += [f"        par.on_fault_vars[0, iz, ix, {i}] = v[{k!r}]"
                  for k, i in EQQUASI_INDEX.items()]
    else:
        keys = {k: i for k, i in EQDYNA_INDEX.items()
                if not (par.mode == 2 and k in EQDYNA_FROM_RESTART)}
        lines += ["par.on_fault_vars = np.zeros((par.nfz, par.nfx, 100))",
                  "for ix, x in enumerate(par.fx):",
                  "    for iz, z in enumerate(par.fz):",
                  "        v = fault(p, x, z)",
                  "        par.on_fault_vars[iz, ix, 1] = par.fric_sw_fs",
                  "        par.on_fault_vars[iz, ix, 2] = par.fric_sw_fd",
                  "        par.on_fault_vars[iz, ix, 3] = par.fric_sw_D0",
                  "        par.on_fault_vars[iz, ix, 14] = par.fric_rsf_fw"]
        lines += [f"        par.on_fault_vars[iz, ix, {i}] = v[{k!r}]"
                  for k, i in keys.items()]
    return "\n".join(lines) + "\n"


def write_code_compset(compset_dir, code, out_dir):
    """Write <out_dir>/user_defined_params.py (+ fault geometry) for code."""
    par, funcs = load_problem(compset_dir)
    os.makedirs(out_dir, exist_ok=True)
    text = render(par, funcs, code, os.path.basename(compset_dir.rstrip("/")))
    with open(os.path.join(out_dir, "user_defined_params.py"), "w") as f:
        f.write(text)
    y = roughness.heights(par, compset_dir)
    if y is not None:
        roughness.write(par, y, os.path.join(out_dir, roughness.FILENAME))
    return par


def upstream_compset_arg(code, out_dir):
    """The compset argument that makes code's create.newcase read out_dir."""
    base = os.path.join(os.environ[ROOT_ENV[code]], COMPSET_DIR[code])
    return os.path.relpath(out_dir, base)
